### ISSUE TITLE
[-] BO : State category hide and show

### ISSUE THREAD

**Issue by indesign47** [zedx/core#29]
change state of a category show to hide and click save - > change not save

**Comment by indesign47** [comment]
You have fixed the issue for BO but it seem that in FO, an hidden category is still showed.

![capture d ecran 2016-08-25 a 15 25 37](https://cloud.githubusercontent.com/assets/10869178/17970808/6034271e-6ad8-11e6-8a5c-e1fe6f557d35.png)
![capture d ecran 2016-08-25 a 15 25 48](https://cloud.githubusercontent.com/assets/10869178/17970816/66571d9a-6ad8-11e6-8c94-bbc2282c88ca.png)

**Comment by zorx** [comment]
Yes, In FO there is already this issue https://github.com/zedx/zedx/issues/12

**Comment by indesign47** [comment]
Sorry, I haven't see this repository !
