### ISSUE TITLE
[-] FO : Can't change picture avatar

### ISSUE THREAD

**Issue by indesign47** [zedx/core#30]

**Comment by zorx** [comment]
There is no issue with the avatar, can you give me more details please (try it on [ZEDx demo version](https://demo.zedx.io))

Which browser do you use ?

**Comment by indesign47** [comment]
Hackintosh
MacOs 10.10.5
Firefox 48.0.1 
Mam Pro 3.5

Tried with the demo version same issue. Click on change button have no effect.
Maybe due to my configuration.

**Comment by zorx** [comment]
Ok I'll try with those browsers

**Comment by indesign47** [comment]
Works fine on Chrome 52.0.2743.116 and Safari 8.0.8 
So the issue is due to Firefox 48.0.1
