### ISSUE TITLE
[+] BO : log-in without information no error

### ISSUE THREAD

**Issue by indesign47** [zedx/core#31]
- When you click on log in (without email or password) no error message
- When you click on log in (with an email and no or bad password) no error message

**Comment by zorx** [comment]
No issue, more details please.

Tested on [ZEDx demo version](https://demo.zedx.io)

## Without email or password

![wi-nothing](https://cloud.githubusercontent.com/assets/4219529/17941755/010a000e-6a35-11e6-9b7f-9556a5acb568.png)

## Bad password

![wrong-password](https://cloud.githubusercontent.com/assets/4219529/17941756/010ba8be-6a35-11e6-99fc-a75739502b1d.png)

**Comment by indesign47** [comment]
Sorry, I made a mistake for this issue is for **BO** not **FO**
![capture d ecran 2016-08-24 a 21 32 01](https://cloud.githubusercontent.com/assets/10869178/17945048/702d8912-6a42-11e6-9e65-4345d29dc36b.png)

**Comment by zorx** [comment]
Yep right, I'll fix it
