### ISSUE TITLE
[+] FO : send an email -> close windows

### ISSUE THREAD

**Issue by indesign47** [zedx/core#32]
When you send an email to the seller the window stay after the click better to close it

**Comment by zorx** [comment]
The sender must know that the message was sent that's why the modal is still there.

**Comment by indesign47** [comment]
I notice the message. 
But maybe, it's better for the user "labda", to back to the ads and show the answer in a message box with an Ok button.

**Comment by zorx** [comment]
Yeah, why not, kind of confirmation message

**Comment by indesign47** [comment]
Yes ! a simple confirmation
