### ISSUE TITLE
[-] FO : ads -> price not show

### ISSUE THREAD

**Issue by indesign47** [zedx/core#33]
The price of a ad doesn't appear...

**Comment by zorx** [comment]
In which part exactly ? can you give me the link from the [demonstration version](https://demo.zedx.io)

## Example : https://demo.zedx.io/ad/show/1/lamborghini-aventador

![ad-price](https://cloud.githubusercontent.com/assets/4219529/17942007/e705d4ca-6a35-11e6-870e-ede03624430a.png)

**Comment by indesign47** [comment]
add a ad with a price not show on my configuration !
![capture d ecran 2016-08-24 a 21 10 43](https://cloud.githubusercontent.com/assets/10869178/17944292/6e2da370-6a3f-11e6-866e-b634331d65e3.png)

**Comment by zorx** [comment]
Because there is no price in your `ad` check it at : https://demo.zedx.io/zxadmin/ad/4/edit

**Comment by indesign47** [comment]
I give a price. Look already to the admin and no price !
I did an another ad with price. No more luck !
![capture d ecran 2016-08-24 a 21 58 05](https://cloud.githubusercontent.com/assets/10869178/17945926/4074a094-6a46-11e6-929e-b9ce5dd88214.png)
![capture d ecran 2016-08-24 a 22 02 07](https://cloud.githubusercontent.com/assets/10869178/17945963/7352f466-6a46-11e6-9884-f664827517a8.png)

**Comment by zorx** [comment]
There is a space between 120 and 000, price is an Integer, so you have to write 120000.

I'll add a Js verification to ensure that everything is correct before sending the form
