### ISSUE TITLE
[+] FO : ads -> navigate with next previous

### ISSUE THREAD

**Issue by indesign47** [zedx/core#34]
Add next-previous to navigate through the list of adds into the same category

![capture d ecran 2016-08-24 a 22 16 58](https://cloud.githubusercontent.com/assets/10869178/17946581/36a1eba0-6a49-11e6-8e10-0c2dca308220.png)

**Comment by zorx** [comment]
I think that it would be greate to create this enhancement as a separate widget called `relatedAds` which gives the Adminstrator the ability to put them where he want.
