### ISSUE TITLE
[+] FO : ads -> sort by date or price

### ISSUE THREAD

**Issue by indesign47** [zedx/core#35]
- add a list box with sort by : Date / Price

![capture d ecran 2016-08-24 a 22 30 18](https://cloud.githubusercontent.com/assets/10869178/17946906/93310e2c-6a4a-11e6-91bd-d9ca0092260f.png)

**Comment by zorx** [comment]
Must run `php artisan migrate --force` and update all the Ads already saved (must be updated from the administration)  to see this feature.
