### ISSUE TITLE
[+] FO : add an ads -> advanced fields reset

### ISSUE THREAD

**Issue by indesign47** [zedx/core#37]
When you add an ad with no title or less than 10 character advanced fields are reset to zero

![capture d ecran 2016-08-25 a 15 55 06](https://cloud.githubusercontent.com/assets/10869178/17972508/42bfba66-6adf-11e6-9e36-82a50eff1753.png)

![capture d ecran 2016-08-25 a 16 18 02](https://cloud.githubusercontent.com/assets/10869178/17972585/8a0c5848-6adf-11e6-827b-91a79489cfc1.png)

**Comment by zorx** [comment]
To test this fix, you have to start the command `gulp` to compile Js files.
