### ISSUE TITLE
[+] BO : add a search field into [Adtypes, users, advancedFields, subscriptions, pages]

### ISSUE THREAD

**Issue by indesign47** [zedx/core#47]
like for ads add a search field

**Comment by zorx** [comment]
It would be great to add a search engine for the whole system (Adtypes, users, advancedFields, subscriptions, pages and later for categories too)

Can you try to do that and make a Pull Request ? 

Views are in `./resources/views/backend/`
Controllers in `./src/Http/Controllers/Backend/`
Models in `./src/Models/`

All you have to do is adding `Eloquence` trait into model with `searchableColumns` attribute (see Ad model)

And then `search(\Request::get('q'))` into controller (see AdController, index() method)

And finaly put the input box into the view file.

I'll really appreciate your contribution.

**Comment by indesign47** [comment]
Thanks for you advice ! Tried a long time but with no success...

**Comment by zorx** [comment]
Ok, I'll do it with `Users` and then you can do the same thing to others

**Comment by indesign47** [comment]
view Subscription add this

```
        <li class="pull-right col-sm-12 col-xs-12 col-sm-4 col-md-3">
          <form action="{{ Request::url() }}" >
            <div class="input-group">
              <input type="text" name="q" class="form-control input-sm pull-right" value="{{ Request::get('q') }}" />
              <div class="input-group-btn">
                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </form>
        </li>
```

model Subscription add bold lines

```
namespace ZEDx\Models;

use Illuminate\Database\Eloquent\Model;
use ZEDx\Events\Subscription\SubscriptionWasDeleted;
**use Sofa\Eloquence\Eloquence;**

class Subscription extends Model
{
    **use Eloquence;**
```

controller Ad

```

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $ads = Ad::with('content')
            ->recents()
            ->search(Request::get('q'))
            ->paginate(20);

        return view_backend('ad.index', compact('ads'));
    }
```

Controller Subscription

```
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $subscriptions = Subscription::paginate(10);

        return view_backend('subscription.index', compact('subscriptions'));
    }
```

**How I add this to the existing function ?**
->search(Request::get('q'))

**Comment by zorx** [comment]
You can use it like : `$subscriptions = Subscription::search(Request::get('q'))->paginate(10);`

Check my commit https://github.com/zedx/core/commit/b39a97067277fee61449b5ac367a94f9d02648c4 you can use the same search template for `subscriptions`

Don't forget the `searchableColumns` attribute in the model

**Comment by zorx** [comment]
I'll do `advancedFields` because it already contain a `search` method, so it's not so easy to do, and let you do `subscriptions` and `pages`

**Comment by indesign47** [comment]
I don't forget the `searchableColumns`

```
  protected $searchableColumns = [
    'content.title' => 10,
    'content.body'  => 5,
  ];
```

I already tried `$subscriptions = Subscription::search(Request::get('q'))->paginate(10);`
But got this
![capture d ecran 2016-08-31 a 22 42 17](https://cloud.githubusercontent.com/assets/10869178/18145642/628ba250-6fcc-11e6-9e91-c5fa35706565.png)

**Comment by indesign47** [comment]
Like you says so it's not so easy to do especially for me !

**Comment by zorx** [comment]
Excuse, it's my fault, you have to use `$subscriptions = Subscription::search(\Request::get('q'))->paginate(10);`

the `searchableColumns` means which field have to be searchable, so in subscriptions we will have `title` and `description`

```
protected $searchableColumns = [
    'title' => 10,
    'description'  => 10,
  ];
```

and for pages we will have `title => 10`, `shortcut => 5` and `description => 10`

Yes `Field` is pretty difficult, but it's Ok for `Subscriptions` and `Pages.`

**Comment by indesign47** [comment]
Bingo ! Works now 👍  Good explication thanks !
