### ISSUE TITLE
[-] BO : dashboard -> config widgets

### ISSUE THREAD

**Issue by indesign47** [zedx/core#67]
button `btn btn-box-tool` has no effect

**Comment by zorx** [comment]
Can you be more clear please

**Comment by indesign47** [comment]
dashboard button `btn btn-box-tool`  "clé à molette" should open the setting of the widget but when you click on nothing more.

![capture d ecran 2016-09-05 a 16 47 05](https://cloud.githubusercontent.com/assets/10869178/18251320/d8ae0dc8-7388-11e6-8922-c77849aa3952.png)

**Comment by zorx** [comment]
Ya, currently there is no config system for dashboard widgets, I'll update the issue name to create it
