### ISSUE TITLE
[-] FO : map -> department strange name

### ISSUE THREAD

**Issue by indesign47** [zedx/core#74]
Some departments show numbers after or before 

Picardi**e**

![capture d ecran 2016-09-14 a 18 06 13](https://cloud.githubusercontent.com/assets/10869178/18519996/46062dfa-7aa6-11e6-98a4-edde4ca315fa.png)
![capture d ecran 2016-09-14 a 18 05 09](https://cloud.githubusercontent.com/assets/10869178/18520106/bb74f26a-7aa6-11e6-91e1-304b6fdf69c8.png)
![capture d ecran 2016-09-14 a 18 05 52](https://cloud.githubusercontent.com/assets/10869178/18520116/c36c6f8e-7aa6-11e6-9b92-86fb6f1b52cb.png)
![capture d ecran 2016-09-14 a 18 06 29](https://cloud.githubusercontent.com/assets/10869178/18520119/c84480fa-7aa6-11e6-91cf-a15f71009efe.png)
![capture d ecran 2016-09-14 a 18 06 48](https://cloud.githubusercontent.com/assets/10869178/18520129/d6fc907e-7aa6-11e6-804b-2a7a7dae26fe.png)

**Comment by zorx** [comment]
Unfortunately this can't be fixed, because it's related to Google maps api

**Comment by indesign47** [comment]
---

**Comment by zorx** [comment]
can you create a discussion at https://discuss.zedx.io/ please ?
